"""add users table and student_profiles.user_id

Revision ID: 1762fe58f085
Revises: 58dd0c876dde
Create Date: 2026-08-17 17:31:50.327127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1762fe58f085'
down_revision: Union[str, Sequence[str], None] = '58dd0c876dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_agent_executions_agent_name'), 'agent_executions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_executions_workflow_id'), 'agent_executions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_workflow_id'), 'agent_messages', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_index(op.f('ix_professors_name'), 'professors', ['name'], unique=False)
    op.add_column('student_profiles', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('uq_student_profiles_email'), 'student_profiles', type_='unique')
    op.create_index(op.f('ix_student_profiles_email'), 'student_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_student_profiles_user_id_users'), 'student_profiles', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_constraint(op.f('fk_student_profiles_user_id_users'), 'student_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_email'), table_name='student_profiles')
    op.create_unique_constraint(op.f('uq_student_profiles_email'), 'student_profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_profiles', 'user_id')
    op.drop_index(op.f('ix_professors_name'), table_name='professors')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_agent_messages_workflow_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_executions_workflow_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_name'), table_name='agent_executions')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
