"""add university faculty_directory_url

Revision ID: 90e7bcbb5a2c
Revises: 05b739a70e8e
Create Date: 2026-08-17 18:47:02.452687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e7bcbb5a2c'
down_revision: Union[str, Sequence[str], None] = '05b739a70e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('faculty_directory_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'faculty_directory_url')
    # ### end Alembic commands ###
